extends SceneTree


func _init() -> void:
	var zona := Node2D.new()
	var suelo := TileMapLayer.new()
	var decoracion := TileMapLayer.new()
	suelo.name = "CapaSuelo"
	decoracion.name = "CapaDecoracion"
	suelo.tile_set = load("res://assets/tile_sets/terrain/cave_terrain.tres")
	decoracion.tile_set = load("res://assets/tile_sets/decorations/rocks_medium.tres")
	zona.add_child(suelo)
	zona.add_child(decoracion)
	suelo.set_cell(Vector2i.ZERO, 0, Vector2i.ZERO)
	suelo.set_cell(Vector2i.RIGHT, 0, Vector2i.ZERO)
	suelo.set_cell(Vector2i.DOWN, 0, Vector2i.ZERO)
	suelo.set_cell(Vector2i(1, 1), 0, Vector2i.ZERO)
	decoracion.set_cell(Vector2i.ZERO, 0, Vector2i(3, 1))
	decoracion.set_cell(Vector2i.RIGHT, 1, Vector2i(30, 1))
	decoracion.set_cell(Vector2i.DOWN, 2, Vector2i(4, 1))
	decoracion.set_cell(Vector2i(1, 1), 3, Vector2i(4, 1))
	var tablero := TableroGrid.new()
	tablero.generar_desde_zona(zona)
	var celda := tablero.obtener_celda(Vector2i.ZERO)
	assert(celda.caminable)
	assert(celda.altura == 1)
	assert(celda.familia_fog == &"roca")
	assert(celda.coordenada_fog == Vector2i(3, 1))
	var ruina := tablero.obtener_celda(Vector2i.RIGHT)
	assert(ruina.caminable and ruina.altura == 1)
	assert(ruina.familia_fog == &"ruina")
	assert(ruina.coordenada_fog == Vector2i(30, 1))
	var huesos := tablero.obtener_celda(Vector2i.DOWN)
	assert(huesos.caminable and huesos.altura == 0)
	assert(huesos.familia_fog == &"terreno")
	assert(huesos.coordenada_fog == Vector2i.ZERO)
	var cadenas := tablero.obtener_celda(Vector2i(1, 1))
	assert(cadenas.caminable and cadenas.altura == 0)
	assert(cadenas.familia_fog == &"terreno")
	var niebla := load("res://assets/tile_sets/fog/cave_fog.tres") as TileSet
	assert(niebla.has_source(16) and niebla.has_source(17))
	zona.free()
	print("OK: rocas y ruinas caminables aportan altura y fog sin bloquear el paso.")
	quit()
